import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
    ],
    safelist: [
        'max-w-2xl',
        'max-w-3xl',
        'max-w-4xl',
        'max-w-5xl',
        'max-w-6xl',
        'max-w-7xl',
        'max-w-8xl',
        'text-3xl', 'text-4xl', 'text-5xl',
        'grid-cols-1',
        'grid-cols-2',
        'grid-cols-3',
        'grid-cols-4',
        'grid-cols-5',
        'grid-cols-6',
        'grid-cols-7',
        'grid-cols-8',
        'grid-cols-9',
        'grid-cols-10',
        'grid-cols-11',
        'grid-cols-12',
        'md:grid-cols-1',
        'md:grid-cols-2',
        'md:grid-cols-3',
        'md:grid-cols-4',
        'md:grid-cols-5',
        'md:grid-cols-6',
        'md:grid-cols-7',
        'md:grid-cols-8',
        'md:grid-cols-9',
        'md:grid-cols-10',
        'md:grid-cols-11',
        'md:grid-cols-12',
        'lg:grid-cols-1',
        'lg:grid-cols-2',
        'lg:grid-cols-3',
        'lg:grid-cols-4',
        'lg:grid-cols-5',
        'lg:grid-cols-6',
        'lg:grid-cols-7',
        'lg:grid-cols-8',
        'lg:grid-cols-9',
        'lg:grid-cols-10',
        'lg:grid-cols-11',
        'lg:grid-cols-12',
        'xl:grid-cols-1',
        'xl:grid-cols-2',
        'xl:grid-cols-3',
        'xl:grid-cols-4',
        'xl:grid-cols-5',
        'xl:grid-cols-6',
        'xl:grid-cols-7',
        'xl:grid-cols-8',
        'xl:grid-cols-9',
        'xl:grid-cols-10',
        'xl:grid-cols-11',
        'xl:grid-cols-12',
    ],

    theme: {
        screens: {
            'sm': '500px',
            'md': [
                {'min': '668px', 'max': '767px'},
                {'min': '868px'}
            ],
            'lg': '1100px',
            'xl': '1400px',
            '2xl': '1600px',
            '3xl': '1800px',
            '4xl': '2200px',
        },
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [forms, typography],
};
